apiVersion: apps/v1
kind: Deployment
metadata:
  name: challenge-app
spec:
  selector:
    matchLabels:
      app: challenge-app
  template:
    metadata:
      labels:
        app: challenge-app
    spec:
      containers:
      - name: challenge-app
        image: culceanluca/py-web
        imagePullPolicy: Always
        resources:
          requests:
            memory: "512Mi"
            cpu: "1000m"
          limits:
            memory: "1024Mi"
            cpu: "5000m"
        ports:
        - containerPort: 5555
