apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
images:
- name: deployment/challenge-app
  newName: culceanluca/py-web
  newTag: dfac2bdccd5932f95d399052ec8773e4e4504915
